stages:
  - dockerize
  - build
  - test
  - deploy

variables:
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_HOST: "tcp://docker:2375"
  DOCKER_DRIVER: "overlay2"

services:
  - name: docker:latest

dockerize_pipeline:
  stage: dockerize
  script:
    - docker build -t yanlkm/chat-app-containers:latest .
    - docker push yanlkm/chat-app-containers:latest

build_image:
  stage: build
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - docker pull yanlkm/chat-app-containers:latest
    - docker run --rm -v /var/run/docker.sock:/var/run/docker.sock yanlkm/chat-app-containers:latest docker build -t yanlkm/chat-app-containers:latest .
    - docker push yanlkm/chat-app-containers:latest

test_image:
  stage: test
  script:
    - docker pull yanlkm/chat-app-containers:latest
    - docker run --rm yanlkm/chat-app-containers:latest go test ./...

deploy_image:
  stage: deploy
  script:
    - docker login -u yanlkm -p $CI_REGISTRY_PASSWORD
    - docker pull yanlkm/chat-app-containers:latest
    - docker run --rm yanlkm/chat-app-containers:latest docker push yanlkm/chat-app-containers:latest
  only:
    - master
