stages:
  - dockerize
  - build
  - test
  - deploy

variables:
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_HOST: "tcp://docker:2375"
  DOCKER_DRIVER: "overlay2"

services:
  - docker:ruby.2.7

dockerize_pipeline:
  stage: dockerize
  image: docker:ruby.2.7
  script:
    - docker build -t yanlkm/chat-app-pipeline:latest .
    - docker push yanlkm/chat-app-pipeline:latest

build_image:
  stage: build
  image: docker:latest
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - docker pull yanlkm/chat-app-pipeline:latest
    - docker build -t yanlkm/chat-app-containers:latest .
    - docker push yanlkm/chat-app-containers:latest

test_image:
  stage: test
  image: yanlkm/chat-app-containers:latest
  script:
    - go test ./...

deploy_image:
  stage: deploy
  image: yanlkm/chat-app-containers:latest
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - docker push yanlkm/chat-app-containers:latest
  only:
    - master
