services:
  mongodb:
    image: yanlkm/mongo:latest
    ports:
      - "27017:27017"

  chat-app:
    image: yanlkm/chat-app:latest
    build:
      context: .
    ports:
    - "8080:8080"
    depends_on:
      - mongodb
